In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4,7,-5,3],index = ['a','b','c','d'])

In [6]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [7]:
obj2['a']

4

In [8]:
obj2[obj2>0]

a    4
b    7
d    3
dtype: int64

In [9]:
'b'in obj2

True

In [10]:
sdata = {'Ohin': 35000,'texas':710000,'oregon':160000,'utah':5000}
obj3 = pd.Series(sdatas)

NameError: name 'sdatas' is not defined

In [11]:
sdata = {'Ohin': 35000,'texas':710000,'oregon':160000,'utah':5000}
obj3 = pd.Series(sdata)

In [12]:
obj3

Ohin       35000
texas     710000
oregon    160000
utah        5000
dtype: int64

In [13]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California   NaN
Ohio         NaN
Oregon       NaN
Texas        NaN
dtype: float64

In [14]:
states = ['California', 'ohio', 'oregon', 'texas']
obj4 = pd.Series(sdata, index=states)
obj4

California         NaN
ohio               NaN
oregon        160000.0
texas         710000.0
dtype: float64

In [15]:
pd.isnull(obj4)

California     True
ohio           True
oregon        False
texas         False
dtype: bool

In [16]:
obj3 + obj4

California          NaN
Ohin                NaN
ohio                NaN
oregon         320000.0
texas         1420000.0
utah                NaN
dtype: float64

In [17]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California         NaN
ohio               NaN
oregon        160000.0
texas         710000.0
Name: population, dtype: float64

In [18]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [19]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [20]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [21]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

SyntaxError: EOL while scanning string literal (<ipython-input-21-ed623d53107c>, line 1)

In [22]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [23]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [24]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [25]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3


Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [26]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [27]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [28]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [29]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b','a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [30]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [31]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [32]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [33]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])
frame

NameError: name 'np' is not defined

In [34]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),index=['a', 'c', 'd'],columns=['Ohio', 'Texas', 'California'])
frame

NameError: name 'np' is not defined

In [35]:
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),index=['a', 'c', 'd'],columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [36]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [37]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [38]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [39]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [40]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah','New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [42]:
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [43]:
obj.drop('c', inplace=True)

In [44]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [45]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [46]:
ser[-1]

KeyError: -1

In [47]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [48]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c','d', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [49]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [50]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [51]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [52]:
arr[0]

array([0., 1., 2., 3.])

In [53]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [54]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
columns=list('bde'),
 index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [55]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [56]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
 index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.209007  0.326226 -1.339762
Ohio   -0.125358 -1.277905  0.179026
Texas   0.495673 -0.102269 -0.375700
Oregon -0.965502 -1.898667  0.534521

In [57]:
np.abs(frame)

b         d         e
Utah    0.209007  0.326226  1.339762
Ohio    0.125358  1.277905  0.179026
Texas   0.495673  0.102269  0.375700
Oregon  0.965502  1.898667  0.534521

In [58]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.461175
d    2.224893
e    1.874283
dtype: float64

In [59]:
frame.apply(f, axis='columns')

Utah      1.665988
Ohio      1.456931
Texas     0.871373
Oregon    2.433188
dtype: float64

In [60]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.21   0.33  -1.34
Ohio    -0.13  -1.28   0.18
Texas    0.50  -0.10  -0.38
Oregon  -0.97  -1.90   0.53

In [61]:
frame['e'].map(format)

Utah      -1.34
Ohio       0.18
Texas     -0.38
Oregon     0.53
Name: e, dtype: object

In [62]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [63]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
index=['three', 'one'],
columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [64]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [65]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [66]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_value()

AttributeError: 'Series' object has no attribute 'sort_value'

In [67]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [68]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [69]:
obj.index.is_unique

False

In [70]:
obj['a']

a    0
a    1
dtype: int64

In [71]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.689065 -0.278097  1.278038
a -0.103048  0.885923 -0.365206
b -0.774905 -0.242879  0.102403
b  1.532189 -1.345394 -2.184094